### ISSUE TITLE
I am getting this error when trying to pull from git

### ISSUE THREAD

**Issue by FunkyMonk8111** [leachim6/hello-world#1394]
Cloning into..
remote: Enumerating objects: 7543, done.        
remote: Counting objects: 100% (507/507), done.        
remote: Compressing objects: 100% (296/296), done.        
remote: Total 7543 (delta 264), reused 370 (delta 154), pack-reused 7036        
Receiving objects: 100% (7543/7543), 5.05 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (3894/3894), done.
error: invalid path '#/*><>'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Can anyone help?

**Comment by MarkusEicher** [comment]
Hi there. I had the same problem when trying to clone this repository. It seems to be a problem with the checkout because of special characters that prevent this repo to be checked out correctly on a Windows machine. I guess you are using Windows because I had the exact same error message. I was able to clone a fork of this repo from a GitHub user called zzl686. Here is the link to his fork, that I was able to clone to my Windows 10 system.

git clone https://github.com/zzl686/hello-world.git

After cloning it, I added the the upstream to the original repo here with the following command:

git remote add upstream https://github.com/leachim6/hello-world.git

So I was able to sync my local clone with the original repo. Thats how my local repo looks like with the remote connections:

$ git remote -v
origin  https://github.com/zzl686/hello-world.git (fetch)
origin  https://github.com/zzl686/hello-world.git (push)
upstream        https://github.com/leachim6/hello-world.git (fetch)
upstream        https://github.com/leachim6/hello-world.git (push)

I use this repo for educational purposes only because it was part of an Udemy Git course and I wanted to follow it, so I needed to clone this repo. Other than cloning the one from zzl686 and then add the original from leachim6 as upstream I had no chance. 

Hope this helps. Have fun and take care

**Comment by Richienb** [comment]
Fixed, for now
