### ISSUE TITLE
Why does pascal have a readline?

### ISSUE THREAD

**Issue by vsoch** [leachim6/hello-world#427]
I'm going through the examples, and for most the standard is to print some version of hello world (note there are differences in what is printed too) and exit. For the pascal script:

https://github.com/leachim6/hello-world/blob/master/p/pascal.p

A readline was added, meaning that the user needs to press enter before exiting. Was there a reason for this?

**Comment by guerrieroi** [comment]
Old style programmers use it when the program writes on the console. If it is omitted, when you run the program from a IDE, the console will be closed immediately after the end of the program and you will not be able to see the text output. Usually, when the program is deployed in a production environment, the pause will be removed.

You can see also the [batch file](https://github.com/leachim6/hello-world/blob/master/b/batch.bat) example where there is a **pause** command that do the same thing.

**Comment by leachim6** [comment]
I'm not super familiar with conventions with Pascal. However, the general idea is to  have the simplest program that prints "Hello World" and quits. Please feel free to contribute an update and I will merge it in.

Thanks!

**Comment by guerrieroi** [comment]
Adding **readline** at the end of a console application is a way to stop the program until the user read the output and hit a key on the keyboard to go on. It was used with old IDE like Turbo Pascal.

There is another example where is used the statement **pause** to wait until the user hit any key: [batch script](https://github.com/leachim6/hello-world/blob/master/b/batch.bat)

**Comment by rdebath** [comment]
No language I've ever come across has the "convention" that you have to add a "Don't exit until a user hits you" statement at the end.

Specifically: 

1. Batch scripts are supposed to be run from a command line where that final statement is just an annoyance.   
2. An IDE is supposed to work much like the oldest ones of all when running command line programs. For example, Vi pauses (with a press return) before wiping away the output you need to see. If the program has this final statement too then you have to do it twice.

Basically, until recently Microsoft have hated the command line and never done anything to make it work correctly. Even the old VBScript, which has a window'd and command line interpreters, makes switching between them very clunky. With Unix environments you generally have to set a tickbox on a link to a command line program so that it's run within a terminal window which waits for the user to close it (if there's any output). Unlike Unix, Microsoft have a flag on the executable for "Console applications" so they actually automatically create the terminal window, but the previously mentioned hatred means they never added the automatic "pause so the output can be read" feature.

Recently, things are changing , eg: after 30 years Microsoft have finally added VT100 style terminal emulation to their terminal window. They seem to like command lines a little bit now.

**Comment by Richienb** [comment]
Same applied for batch.
