### ISSUE TITLE
Removing spoken languages?

### ISSUE THREAD

**Issue by Richienb** [leachim6/hello-world#891]
Since spoken languages aren't computer languages, should they be removed?

**Comment by arya2910** [comment]
indeed spoken languages should be included .since programming languages is somewhere between spoken language use by users and binary code understand by computers it gives us platform to connect user and computer directly. programming languages allows us to reason about their syntax and their grammar rules, the semantics of certain expressions, and so on.

**Comment by arya2910** [comment]
Indeed!! spoken language should be included. It provides a base to programming languages. since programming languages is the way to connect the spoken language(use by users) to binary code(understands by computer). we made programming languages with the help of spoken languages only and its easier to reason the grammars and syntax of programming languages.

**Comment by MrBrain295** [comment]
@Richienb shouldn’t this be closed?
